server.host: "kibana"
server.port: 5601
server.name: kibana

elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: ${ELASTICSEARCH_USERNAME}
elasticsearch.password: ${ELASTICSEARCH_PASSWORD}

