server:
  name: kibana
  host: "0.0.0.0"
  port: 5601

elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  elasticsearch.username: ${ELASTIC_USERNAME}
  elasticsearch.password: ${ELASTIC_PASSWORD}
